### ISSUE TITLE
[國際服] 按添加沒反應

### ISSUE THREAD

**Issue by MrLuke1110** [genshin-matrix/genshin-switch#1]
請問是不支援國際服，或是不支援正體中文的 Windows 10，
按了添加的按鈕沒有顯示任何畫面，謝謝

**Comment by emako** [comment]
那个，咱没有国际服的号，应该是测试上有些欠缺，跟正体没什么关系。

**Comment by emako** [comment]
这个fork的分支[https://github.com/Jomata/genshin-switch](https://github.com/Jomata/genshin-switch)软件能正常工作吗？

**Comment by MrLuke1110** [comment]
> 这个fork的分支https://github.com/Jomata/genshin-switch软件能正常工作吗？

可以正常使用

**Comment by emako** [comment]
能发一下log么？
![image](https://user-images.githubusercontent.com/24737061/221622006-d7ee2ea8-6e89-4a20-97f3-3e068bcb2dcc.png)

**Comment by MrLuke1110** [comment]
> 能发一下log么？ 

提供LOG如下
[20230228.log](https://github.com/genshin-matrix/genshin-switch/files/10845851/20230228.log)

**Comment by emako** [comment]
瞅了一眼log大概能定位问题原因应该是国际服支持有点问题。

**Comment by emako** [comment]
比较尴尬的是不太确定好不好使：[v2.0.10](https://github.com/genshin-matrix/genshin-switch/releases/tag/v2.0.10)

**Comment by MrLuke1110** [comment]
> 比较尴尬的是不太确定好不好使：[v2.0.10](https://github.com/genshin-matrix/genshin-switch/releases/tag/v2.0.10)

可以正常使用，感謝更新~~

不過，LOG檔案中有些奇怪的路徑，若是可以調整就正好，感謝。
![image](https://user-images.githubusercontent.com/66194793/222493940-f61db9fc-4701-4128-a4c1-7f9b73e00841.png)

**Comment by emako** [comment]
路径是正确且正常的，因为优先了国服的获取，然后才是国际服。
